apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: root
  project: root-argo
  source:
    path: charts/argo-cd
    repoURL: https://github.com/oscarWoj/webbysite.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
