apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #argocd.argoproj.io/sync-wave: "-2"
  name: harbor
  namespace: default

spec:
  project: default
  source:
    chart: harbor
    #helm:
     # values:
      
    repoURL: https://helm.goharbor.io
    targetRevision: 1.9.1
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    automated:
      selfHeal: true
      prune: true


#            cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
#            external-dns.alpha.kubernetes.io/hostname: opencart.ghgsat.science
#            kubernetes.io/ingress.class: nginx
#            kubernetes.io/tls-acme: "true"
#ingress:
          #enabled: true
