apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #argocd.argoproj.io/sync-wave: "-2"
  name: opencart
  namespace: default

spec:
  project: default 

  source:
    chart: opencart
    helm:
      values: |
        allowEmptyPassword: false
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: opencart.ghgsat
        replicaCount: 1
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.5
  destination:
    server: https://kubernetes.default.svc
    namespace: opencart

  syncPolicy:
  # uncomment to create namespace if not present annotations ####
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
