apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #argocd.argoproj.io/sync-wave: "-2"
  name: pypi-nocgp
  namespace: default

spec:
  project: default
  source:
    repoURL: 'https://github.com/oscarWoj/myPypi.git'
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true


#            cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
#            external-dns.alpha.kubernetes.io/hostname: opencart.ghgsat.science
#            kubernetes.io/ingress.class: nginx
#            kubernetes.io/tls-acme: "true"