apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #argocd.argoproj.io/sync-wave: "-2"
  name: pypi-server
  namespace: default

spec:
  project: default
  source:
    chart: pypiserver
    helm:
      #values: |
        #ingress:
          #enabled: true
    repoURL: https://owkin.github.io/charts
    targetRevision: 3.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: pypi-server

  syncPolicy:
    automated:
  #    selfHeal: true
      prune: true


#            cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
#            external-dns.alpha.kubernetes.io/hostname: opencart.ghgsat.science
#            kubernetes.io/ingress.class: nginx
#            kubernetes.io/tls-acme: "true"
