apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: root
  source:
    path: apps/
    repoURL: https://github.com/oscarWoj/webbysite.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
